#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

#Cosas

setxkbmap latam

#Polybar
$HOME/.config/polybar/launch.sh

#$HOME/polybar-collection/launch.sh

#Wallpaper
nitrogen --restore &

#Transparencias
picom -f &

#Cursor
lxapperance &

#lockscreen wallpaper
betterlockscreen -u ~/Pictures/Wallpapers/wallhaven-n6lke6.jpg


# ~/.config/bspwm/bspwmrc
xautolock -time 30 -locker "betterlockscreen -l" &
