#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

#bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Colores (Catppuccin Mocha)
bspc config normal_border_color   "#313244"
bspc config active_border_color   "#45475a"
bspc config focused_border_color  "#cba6f7"
bspc config presel_feedback_color "#f5c2e7"

xrandr --output DP-3 --mode 1920x1080 --rate 180 --pos 0x0 --primary
xrandr --newmode "1920x1080_75.00"  220.75  1920 2056 2264 2608  1080 1083 1088 1130 -hsync +vsync
xrandr --addmode HDMI-1 "1920x1080_75.00"
xrandr --output HDMI-1 --mode "1920x1080_75.00" --right-of DP-3

#xrandr --output HDMI-1 --off
#xrandr --output DP-3 --mode 1920x1080 --rate 180 --pos 0x0 --primary
#xrandr --output HDMI-1 --mode 1920x1080 --rate 80 --pos 0x0 --right-of DP-3
#xrandr --output DP-3 --mode 1920x1080 --pos 0x0 --primary
#xrandr --output HDMI-1 --mode 1920x1080 --pos 1920x0 --right-of DP-3

# 2. Asignación de escritorios en bspwm
#bspc monitor DP-3 -d 一 二 三 四 五 六 七 八 九 十
#bspc monitor HDMI-1 -d 一 二 三 四 五 六 七 八 九 十

bspc monitor DP-4 -d 一 二 三 四 五
bspc monitor HDMI-0 -d 六 七 八 九 十

#Cosas

setxkbmap latam

#Polybar
$HOME/.config/polybar/launch.sh

#$HOME/polybar-collection/launch.sh

#Wallpaper
#feh --bg-fill Downloads/wall1.jpg
nitrogen --restore &

#Transparencias
pgrep -x picom >/dev/null || picom -b

#Cursor
xsetroot -cursor_name left_ptr &

#lockscreen wallpaper
betterlockscreen -u ~/Pictures/Wallpapers/wallhaven-n6lke6.jpg

# ~/.config/bspwm/bspwmrc
xautolock -time 30 -locker "betterlockscreen -l" &
